name: df
description: A dataframe for Dart
author: synw <ansterj@gmail.com>
homepage: https://github.com/synw/df
version: 0.0.1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  meta: ^1.1.6
  pedantic: ^1.6.0
  extra_pedantic: ^1.1.1+2
  ml_linalg: ^12.3.0

dev_dependencies:
  test: ^1.6.5
  test_coverage: ^0.3.0+1
