name: dartaframe
description: A dataframe for Dart. An abstraction to help manipulating and analysing data, designed for sdartistics.
homepage: https://github.com/1105420698/dartaframe
version: 0.0.3

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  jiffy: ^4.0.0
  meta: ^1.7.0

dev_dependencies:
  lints: ^1.0.1
  test: ^1.16.5
