name: dartaframe
description: A dataframe for Dart. An abstraction to help manipulating and analysing data, designed for sdartistics.
homepage: https://github.com/1105420698/dartaframe
version: 0.0.1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  lint: ^1.0.0
  jiffy: ^4.0.0
  meta: <1.5.0

dev_dependencies:
  test: ^1.16.5
  test_coverage: ^0.5.0
